### ISSUE TITLE
kibana service not working 

### ISSUE THREAD

**Issue by cstoehr** [mrlesmithjr/ansible-elk-kibana#2]
Hi, 

the kibana service is not working in Ubuntu 16.04. Can you fix it?

cheers

**Comment by mrlesmithjr** [comment]
Hey @cstoehr Sorry just got to this finally. If you have not already found a working Ubuntu 16.04 install I have finally fixed this. I ended up moving to the package installer for Ubuntu.

**Comment by cstoehr** [comment]
THX

**Comment by cstoehr** [comment]
Good Work :)
